package
{
	import mx.collections.ArrayCollection;
	import mx.core.FlexGlobals;

	public class config
	{	
		
		[Bindable]public static var appWidth:Number = FlexGlobals.topLevelApplication.width;
		[Bindable]public static var appHeight:Number = FlexGlobals.topLevelApplication.height;
		
		[Bindable]public static var actionBarHeight:Number = 70;
		
		
		[Bindable]public static var actionBarColor:uint = 0x85BD40;
		
		public static var traders: ArrayCollection = new ArrayCollection([
			{id: '1', tname: 'The Yard', 
						tagline: 'Coffee and Food', 
						photo: 'assets/trader_images/cards/the_yard_banner.png', 
						trader_type: 'assets/app/icons/coffee.png', 
						color: '0x3A1C00', 
						card_offset: '0', 
						offer:'Buy 5 coffees and get 1 free!', 
						lat:'54.0483287',
						lon:'-2.8027303',
						postcode:'LA1 1DN', 
						pname:'Robert Smith',
						facebook:'https://www.facebook.com/TheYardCoffee',
						twitter:'https://twitter.com/yard_coffee',
						url:'',
						email:'theyardcoffee@gmail.com',
						phone:'01524 847393',
						joined:'28-02-2014',
						level:"5",
						has_respent:'yes'},
			{id: '2', tname: 'Simply Flowers by Nicola', 
						tagline: 'Bespoke floral designs for every occasion', 
						photo: 'assets/trader_images/cards/simply_flowers_banner.png', 
						trader_type: 'assets/app/icons/flower.png', 
						color: '0x8563b7', 
						card_offset: '-20', 
						offer:'On your 10th visit, receive 10% of your purchase',
						lat:'54.0324865',
						lon:'-2.7940889',
						postcode:'LA1 4SA', 
						pname:'Nicola Harrison',
						facebook:'https://www.facebook.com/SimplyFlowersbyNicola?ref=hl',
						twitter:'https://twitter.com/Nicola3Harrison',
						url:'http://simplyflowersbynicola.com/',
						email:'simplyflowers1@btinternet.com',
						phone:'01524 388329',
						joined:'21-02-2014',
						level:"4",
						has_respent:'yes'},
			{id: '3', tname: 'The Borough', 
						tagline: 'Fine Ale, Food, Wine and Rooms', 
						photo: 'assets/trader_images/cards/the_borough_banner.png', 
						trader_type: 'assets/app/icons/restaurant.png', 
						color: '0x264d42', 
						card_offset: '-20', 
						offer:'Spend £25 on your food and receive £5 off your bill',
						lat:'54.0480066',
						lon:'-2.7971036',
						postcode:'LA1 1PP', 
						pname:'Jodie Southern',
						facebook:'https://www.facebook.com/TheBoroughLancaster',
						twitter:'https://twitter.com/TheBoroughLancs',
						url:'http://www.theboroughlancaster.co.uk/',
						email:'theyardcoffee@gmail.com',
						phone:'01524 64170',
						joined:'14-03-2014',
						level:"1",
						has_respent:'no'},
			{id: '4', tname: 'The Bed Company', 
						tagline: 'We Offer Good Quality,Great Service and Years Of Experience.', 
						photo: 'assets/trader_images/cards/bed_company_banner.png', 
						trader_type: 'assets/app/icons/bed.png', 
						color: '0x408da9', 
						card_offset: '-20', 
						offer:'10% off every purchase',
						lat:'54.0457974',
						lon:'-2.7995354',
						postcode:'LA1 1XN', 
						pname:'Bill Grant',
						facebook:'',
						twitter:'',
						url:'http://www.lancasterbedcompany.co.uk/',
						email:'lancasterbedcompany@gmail.com',
						phone:'01524 874382',
						joined:'26-03-2014',
						level:"2",
						has_respent:'yes'},
			{id: '5', tname: 'Knight Time Creations', 
						tagline: 'Illustrator and Designer in Lancaster', 
						photo: 'assets/trader_images/cards/knight_time_banner.png', 
						trader_type: 'assets/app/icons/design.png', 
						color: '0xe80d9f', 
						card_offset: '-20',
						offer:'' ,
						lat:'54.0383863',
						lon:'-2.788063',
						postcode:'LA1 3AD', 
						pname:'Jack Knight',
						facebook:'https://www.facebook.com/IllustratorForHire',
						twitter:'https://twitter.com/KnightTCreation',
						url:'http://jack-knight.graphics/',
						email:'jack@knighttimecreations.com',
						phone:'',
						joined:'27-03-2014',
						level:"2",
						has_respent:'yes'},
			{id: '6', tname: 'Small Green Consultancy', 
						tagline: 'Creative Solutions to Social and Environmental Businesses', 
						photo: 'assets/trader_images/cards/small_green_banner.png', 
						trader_type: 'assets/app/icons/business.png', 
						color: '0x84b635', 
						card_offset: '-20', 
						offer:'',
						lat:'54.059649298608',
						lon:'-2.88035999808926',
						postcode:'LA3 1HZ', 
						pname:'Michael Hallam',
						facebook:'https://www.facebook.com/michael.hallam3',
						twitter:'https://twitter.com/lancasteresta',
						url:'http://www.smallgreenconsultancy.co.uk/',
						email:'mike@smallgreenconsultancy.co.uk',
						phone:'',
						joined:'22-01-2014',
						level:"3",
						has_respent:'yes'}
		]);
	}
}